import { useCallback, useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import type { StatsBrief } from '@/domain/statsBrief';
import {
  clearCachedInsights,
  generateAiInsights,
  getCachedInsights,
  setCachedInsights,
} from '@/services/aiInsights';
import { formatAiInsightsHtml } from '@/services/aiInsightsFormat';
import { LiteMaaSClientError } from '@/services/litemaasClient';
import {
  getStoredLiteMaaSSettings,
  isLiteMaaSConfigured,
} from '@/utils/litemaasSettings';

type Props = {
  cacheKey: string;
  brief: StatsBrief;
  disabled?: boolean;
};

export function AiInsightsSection({ cacheKey, brief, disabled = false }: Props) {
  const [text, setText] = useState<string | null>(() => getCachedInsights(cacheKey));
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    setText(getCachedInsights(cacheKey));
    setError(null);
    setCopied(false);
  }, [cacheKey]);

  const run = useCallback(
    async () => {
      const settings = getStoredLiteMaaSSettings();
      if (!isLiteMaaSConfigured(settings)) {
        setError(null);
        return;
      }

      setLoading(true);
      setError(null);
      try {
        const result = await generateAiInsights(settings, brief);
        setCachedInsights(cacheKey, result);
        setText(result);
      } catch (e) {
        const msg =
          e instanceof LiteMaaSClientError
            ? e.message
            : e instanceof Error
              ? e.message
              : 'Failed to generate insights.';
        setError(msg);
      } finally {
        setLoading(false);
      }
    },
    [brief, cacheKey],
  );

  const onRegenerate = () => {
    clearCachedInsights(cacheKey);
    setText(null);
    void run();
  };

  const onCopy = async () => {
    if (!text) return;
    try {
      await navigator.clipboard.writeText(text);
      setCopied(true);
      window.setTimeout(() => setCopied(false), 2000);
    } catch {
      setError('Could not copy to clipboard.');
    }
  };

  const settings = getStoredLiteMaaSSettings();
  const configured = isLiteMaaSConfigured(settings);

  return (
    <div className="ai-insights">
      <div className="ai-insights-header">
        <h4 className="ai-insights-title">AI coaching insights</h4>
        <p className="muted ai-insights-lead">
          Summarizes key patterns and what the numbers may mean for your team. Generated by your LiteMaaS model.
        </p>
      </div>

      {!configured ? (
        <p className="ai-insights-setup muted">
          Add your LiteMaaS API key and LiteLLM base URL in{' '}
          <Link to="/settings">Settings</Link> to enable insights.
        </p>
      ) : (
        <div className="ai-insights-actions">
          <button
            type="button"
            className="btn btn-secondary btn-sm"
            disabled={disabled || loading}
            onClick={() => (text ? onRegenerate() : void run())}
          >
            {loading ? 'Generating…' : text ? 'Regenerate insights' : 'Generate insights'}
          </button>
          {text ? (
            <button
              type="button"
              className="btn btn-secondary btn-sm"
              disabled={loading}
              onClick={() => void onCopy()}
            >
              {copied ? 'Copied' : 'Copy'}
            </button>
          ) : null}
        </div>
      )}

      {error ? <p className="ai-insights-error" role="alert">{error}</p> : null}

      {text ? (
        <div
          className="ai-insights-body"
          dangerouslySetInnerHTML={{ __html: formatAiInsightsHtml(text) }}
        />
      ) : configured && !loading && !error ? (
        <p className="muted ai-insights-hint">Tap Generate insights to analyze the stats below.</p>
      ) : null}

      {loading ? <p className="muted ai-insights-hint">Analyzing stats…</p> : null}
    </div>
  );
}
